# Generated by Selenium IDE

import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


driver = webdriver.Chrome()
vars = {}

  

driver.get("https://www.imagetotext.info/")
driver.set_window_size(974, 1029)
# driver.find_element(By.CSS_SELECTOR, ".browse-dropbtn > label").click()
driver.find_element(By.XPATH, "/html/body/section[1]/div/div[1]/div[1]/div/div/div[1]/div/input[1]").send_keys("C:\\Users\\kanzh\\Desktop\\yolo-opencv-detector-main\\captcha-pict.jpg")
# driver.find_element(By.ID, "jsShadowRoot").click()
# value = driver.find_element(By.ID, "imagetotext_result0").get_attribute("value")
print(value)
# WebDriverWait(self.driver, 30).until(expected_conditions.text_to_be_present_in_element((By.ID, "imagetotext_result0"), "5000"))
  
